server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/orlandoKuanDev/bootcamp-everis-project-1.git
          searchPaths: config-data
          username: ${GITUSER}
          password: ${GITPASS}